apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: kickoff
  labels:
    app: game
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: game
  ports:
  - name: grpc
    port: 9082
    targetPort: 9082
    protocol: TCP
