apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service
  namespace: kickoff
  labels:
    app: leaderboard
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: leaderboard
  ports:
  - name: grpc
    port: 9084
    targetPort: 9084
    protocol: TCP
